# Tutorial :: Threats and opportunities in external data - the power of the news

**CONCERN**

You are working for a consultancy firm in charge of the Australian government's political image. In September 2021, the Australian government had a [high-profile problem with France](https://www.theguardian.com/australia-news/2021/sep/16/australia-nuclear-submarine-deal-contract-france-scrapped-defence-pact-us-uk) due to a deal to buy French submarines being called off. A report has already been generated with the titles of news items. However, your job as an analyst is to create a more thorough report taking into consideration additional information inside each news item.

In particular, your clients want to be aware of **threats** and **opportunities** suggested by the news.

1. **Q**uestion
2. **D**ata
3. **A**nalysis
4. **V**isualisation
5. **I**nsight

<img src="graphics/QDAVI_cycle_sm.png" width="50%" />

### 1. Question

How has the news affected the image of the Australian government?

**Tip:** You can combine web scraping and APIs

### 2. Data

We will use The Guardian API again.

**Tip:** Check the lecture and tutorial notebooks from Week 3 for information about how to call the guardian API

In [1]:
# Libraries for the analysis
import pandas as pd
import requests
import time
import json
from bs4 import BeautifulSoup

In [2]:
# Build a search URL
baseUrl = 'https://content.guardianapis.com/search?q=' # content search

searchString = "submarine"
section = "&section=world"
tag = "&tag=politics/politics"
fromDate = "&from-date=2021-09-01"
toDate = "&to-date=2021-11-30"
with open('private/guardian_key.txt', 'r') as file:
    key = file.read().strip()
api_key = f"&api-key={key}"

url = baseUrl+'"'+searchString+'"'+section+fromDate+toDate+api_key
print(url[:130])

https://content.guardianapis.com/search?q="submarine"&section=world&from-date=2021-09-01&to-date=2021-11-30&api-key=bff5b0ac-e949-

In [3]:
# Call the API
response = requests.get(url)
data = json.loads(response.content)
resp_data = data['response']
resp_data

{'status': 'ok',
 'userTier': 'developer',
 'total': 59,
 'startIndex': 1,
 'pageSize': 10,
 'currentPage': 1,
 'pages': 6,
 'orderBy': 'relevance',
 'results': [{'id': 'world/2021/oct/31/macron-accuses-australian-pm-of-lying-over-submarine-deal',
   'type': 'article',
   'sectionId': 'world',
   'sectionName': 'World news',
   'webPublicationDate': '2021-10-31T19:27:45Z',
   'webTitle': 'Macron accuses Australian PM of lying over submarine deal',
   'webUrl': 'https://www.theguardian.com/world/2021/oct/31/macron-accuses-australian-pm-of-lying-over-submarine-deal',
   'apiUrl': 'https://content.guardianapis.com/world/2021/oct/31/macron-accuses-australian-pm-of-lying-over-submarine-deal',
   'isHosted': False,
   'pillarId': 'pillar/news',
   'pillarName': 'News'},
  {'id': 'world/2021/oct/07/aukus-french-contractor-astonished-at-cancellation-of-australia-submarine-deal',
   'type': 'article',
   'sectionId': 'world',
   'sectionName': 'World news',
   'webPublicationDate': '2021-10-07T16:39:54Z',
   'webTitle': 'Aukus: French contractor ‘astonished’ at cancellation of Australia submarine deal',
   'webUrl': 'https://www.theguardian.com/world/2021/oct/07/aukus-french-contractor-astonished-at-cancellation-of-australia-submarine-deal',
   'apiUrl': 'https://content.guardianapis.com/world/2021/oct/07/aukus-french-contractor-astonished-at-cancellation-of-australia-submarine-deal',
   'isHosted': False,
   'pillarId': 'pillar/news',
   'pillarName': 'News'},
  {'id': 'world/2021/nov/09/australia-promises-jobs-to-workers-stranded-by-scrapping-of-french-submarine-deal',
   'type': 'article',
   'sectionId': 'world',
   'sectionName': 'World news',
   'webPublicationDate': '2021-11-08T16:30:35Z',
   'webTitle': 'Australia promises jobs to workers stranded by scrapping of French submarine deal',
   'webUrl': 'https://www.theguardian.com/world/2021/nov/09/australia-promises-jobs-to-workers-stranded-by-scrapping-of-french-submarine-deal',
   'apiUrl': 'https://content.guardianapis.com/world/2021/nov/09/australia-promises-jobs-to-workers-stranded-by-scrapping-of-french-submarine-deal',
   'isHosted': False,
   'pillarId': 'pillar/news',
   'pillarName': 'News'},
  {'id': 'world/2021/oct/29/biden-admits-macron-us-was-clumsy-submarine-deal',
   'type': 'article',
   'sectionId': 'world',
   'sectionName': 'World news',
   'webPublicationDate': '2021-10-29T17:06:48Z',
   'webTitle': 'Biden admits to Macron the US was ‘clumsy’ in Aukus submarine deal',
   'webUrl': 'https://www.theguardian.com/world/2021/oct/29/biden-admits-macron-us-was-clumsy-submarine-deal',
   'apiUrl': 'https://content.guardianapis.com/world/2021/oct/29/biden-admits-macron-us-was-clumsy-submarine-deal',
   'isHosted': False,
   'pillarId': 'pillar/news',
   'pillarName': 'News'},
  {'id': 'world/2021/oct/01/fears-australias-france-submarine-snub-could-scupper-closer-eu-economic-ties',
   'type': 'article',
   'sectionId': 'world',
   'sectionName': 'World news',
   'webPublicationDate': '2021-10-01T09:00:58Z',
   'webTitle': 'Fears Australia’s France submarine snub could scupper closer EU economic ties',
   'webUrl': 'https://www.theguardian.com/world/2021/oct/01/fears-australias-france-submarine-snub-could-scupper-closer-eu-economic-ties',
   'apiUrl': 'https://content.guardianapis.com/world/2021/oct/01/fears-australias-france-submarine-snub-could-scupper-closer-eu-economic-ties',
   'isHosted': False,
   'pillarId': 'pillar/news',
   'pillarName': 'News'},
  {'id': 'world/2021/oct/28/australias-foreign-minister-to-meet-french-ambassador-in-bid-to-heal-submarine-rift',
   'type': 'article',
   'sectionId': 'world',
   'sectionName': 'World news',
   'webPublicationDate': '2021-10-28T04:39:00Z',
   'webTitle': 'Australia’s foreign minister to meet French ambassador in bid to heal submarine rift ',
   'webUrl': 'https://www.theguardian.com/world/2021/oct/28/australias-foreign-minister-to-meet-french-ambassador-in-bid-to-heal-submarine-rift',
   'apiUrl': 'https://content.guardianapis.com/world/2021/oct/28/australias-foreign-minister-to-meet-french-ambassador-in-bid-to-heal-submarine-rift',
   'isHosted': False,
   'pillarId': 'pillar/news',
   'pillarName': 'News'},
  {'id': 'world/2021/sep/29/former-us-navy-secretary-now-scott-morrisons-aukus-middle-man-on-submarine-plan',
   'type': 'article',
   'sectionId': 'world',
   'sectionName': 'World news',
   'webPublicationDate': '2021-09-29T02:50:32Z',
   'webTitle': 'Former US navy secretary now Scott Morrison’s Aukus middleman on submarine plan',
   'webUrl': 'https://www.theguardian.com/world/2021/sep/29/former-us-navy-secretary-now-scott-morrisons-aukus-middle-man-on-submarine-plan',
   'apiUrl': 'https://content.guardianapis.com/world/2021/sep/29/former-us-navy-secretary-now-scott-morrisons-aukus-middle-man-on-submarine-plan',
   'isHosted': False,
   'pillarId': 'pillar/news',
   'pillarName': 'News'},
  {'id': 'world/2021/sep/16/stab-in-the-back-french-fury-australia-scraps-submarine-deal',
   'type': 'article',
   'sectionId': 'world',
   'sectionName': 'World news',
   'webPublicationDate': '2021-09-16T11:32:12Z',
   'webTitle': '‘Stab in the back’: French fury as Australia scraps submarine deal',
   'webUrl': 'https://www.theguardian.com/world/2021/sep/16/stab-in-the-back-french-fury-australia-scraps-submarine-deal',
   'apiUrl': 'https://content.guardianapis.com/world/2021/sep/16/stab-in-the-back-french-fury-australia-scraps-submarine-deal',
   'isHosted': False,
   'pillarId': 'pillar/news',
   'pillarName': 'News'},
  {'id': 'world/2021/nov/19/naughty-guy-top-chinese-diplomat-accuses-australia-of-sabre-wielding-with-nuclear-submarine-deal',
   'type': 'article',
   'sectionId': 'world',
   'sectionName': 'World news',
   'webPublicationDate': '2021-11-18T16:30:10Z',
   'webTitle': '‘Naughty guy’: top Chinese diplomat accuses Australia of ‘sabre wielding’ with nuclear submarine deal',
   'webUrl': 'https://www.theguardian.com/world/2021/nov/19/naughty-guy-top-chinese-diplomat-accuses-australia-of-sabre-wielding-with-nuclear-submarine-deal',
   'apiUrl': 'https://content.guardianapis.com/world/2021/nov/19/naughty-guy-top-chinese-diplomat-accuses-australia-of-sabre-wielding-with-nuclear-submarine-deal',
   'isHosted': False,
   'pillarId': 'pillar/news',
   'pillarName': 'News'},
  {'id': 'world/2021/sep/20/we-felt-fooled-france-still-furious-after-australia-scraps-90bn-submarine-deal',
   'type': 'article',
   'sectionId': 'world',
   'sectionName': 'World news',
   'webPublicationDate': '2021-09-20T01:11:38Z',
   'webTitle': '‘We felt fooled’: France still furious after Australia scraps $90bn submarine deal',
   'webUrl': 'https://www.theguardian.com/world/2021/sep/20/we-felt-fooled-france-still-furious-after-australia-scraps-90bn-submarine-deal',
   'apiUrl': 'https://content.guardianapis.com/world/2021/sep/20/we-felt-fooled-france-still-furious-after-australia-scraps-90bn-submarine-deal',
   'isHosted': False,
   'pillarId': 'pillar/news',
   'pillarName': 'News'}]}

In [4]:
def get_all_articles_for_response(response_json,full_url):
    total_pages = response_json['pages']
    total_articles = response_json['total']
    print(f"Fetching {total_articles} articles from {total_pages} pages...")
    all_articles = []
    page1_articles = response_json['results']
    all_articles.extend(page1_articles)
    print("Added articles for page: 1")
    
    for page in range(2,total_pages+1):
        print("Getting articles from API for page:",page)
        page_response = requests.get(full_url+f"&page={page}")
        page_data = page_response.json()['response']
        print("Processing results for page:",page_data['currentPage'])
        page_articles = page_data['results']
        print(f"Fetched {len(page_articles)} articles.")
        all_articles.extend(page_articles)
        print("Added articles for page:",page)
        print(f"Status: {len(all_articles)} articles.")
        time.sleep(1) # make sure we're not hitting the API to hard
    
    print(f"FINISHED: Fetched {len(all_articles)} articles.")
    return all_articles

results = get_all_articles_for_response(resp_data,url)

Fetching 59 articles from 6 pages...
Added articles for page: 1
Getting articles from API for page: 2
Processing results for page: 2
Fetched 10 articles.
Added articles for page: 2
Status: 20 articles.
Getting articles from API for page: 3
Processing results for page: 3
Fetched 10 articles.
Added articles for page: 3
Status: 30 articles.
Getting articles from API for page: 4
Processing results for page: 4
Fetched 10 articles.
Added articles for page: 4
Status: 40 articles.
Getting articles from API for page: 5
Processing results for page: 5
Fetched 10 articles.
Added articles for page: 5
Status: 50 articles.
Getting articles from API for page: 6
Processing results for page: 6
Fetched 9 articles.
Added articles for page: 6
Status: 59 articles.
FINISHED: Fetched 59 articles.

In [5]:
# # You can save the articles as a json file

# file_path = "data/"
# file_name = "submarine_articles.json"

# with open(f"{file_path}{file_name}",'w', encoding='utf-8') as fp:
#     fp.write(json.dumps(results))

The results contain the URL to the news items on the website. After inspecting a couple of pages, which information could be easily extracted from it

In [6]:
# Get HTML function
def get_HTML(url):
    # get data from server
    response = requests.get(url)
    html = response.content
    return html

In [7]:
# Beautiful soup function for subtitle
def extract_subtitle(HTML):
    soup = BeautifulSoup(HTML, "html.parser") # the html input and the parser name
    article = soup.find("article") # the tag that contains the article
    div_element = article.find("div", attrs={"data-gu-name": "standfirst"}) # the tag that can be found using an attribute
    if div_element is not None:
        target_element = div_element.find("p")
        return target_element.text
    else:
        return ""

In [8]:
# Beautiful soup function for body
def extract_body(HTML):
    soup = BeautifulSoup(HTML, "html.parser") # the html input and the parser name
    article = soup.find("article") # the tag that contains the article
    div_element = article.find("div", attrs={"id": "maincontent"}) # the tag that can be found using an attribute
    if div_element is not None:
        div_div_element = div_element.find("div")
        target_elements = div_element.find_all("p")
        result = ""
        for te in target_elements:
            result += te.text
        return result
    else:
        return ""

#### Clean/preprocess data

In [9]:
# Create a dataframe
df = pd.DataFrame(columns=["Date", "Section", "Title", "Subtitle", "Body"])
df

Empty DataFrame
Columns: [Date, Section, Title, Subtitle, Body]
Index: []

In [10]:
# Populate the dataframe
for news in results:
    html = get_HTML(news["webUrl"])
    data = {"Date": news["webPublicationDate"], "Section": news["sectionName"], "Title": news["webTitle"], "Subtitle": extract_subtitle(html), "Body": extract_body(html)}
    df_to_append = pd.DataFrame([data])
    df = pd.concat([df,df_to_append], ignore_index=True)
df

,Date,Section,Title,Subtitle,Body
0,2021-10-31T19:27:45Z,World news,Macron accuses Australian PM of lying over sub...,French president criticises Scott Morrison and...,Emmanuel Macron has accused the Australian pri...
1,2021-10-07T16:39:54Z,World news,Aukus: French contractor ‘astonished’ at cance...,Head of Naval Group reiterates company’s ‘stup...,The head of the French defence contractor Nava...
2,2021-11-08T16:30:35Z,World news,Australia promises jobs to workers stranded by...,Defence industry minister Melissa Price tells ...,“Each and every” skilled shipbuilding worker a...
3,2021-10-29T17:06:48Z,World news,Biden admits to Macron the US was ‘clumsy’ in ...,American president moves to repair relationshi...,Joe Biden has moved to repair his damaged pers...
4,2021-10-01T09:00:58Z,World news,Fears Australia’s France submarine snub could ...,Opposition accuses Scott Morrison of failing ‘...,The postponement of trade talks between the Eu...
5,2021-10-28T04:39:00Z,World news,Australia’s foreign minister to meet French am...,Marise Payne says she regrets France’s ‘deep d...,Australia’s foreign minister will meet with th...
6,2021-09-29T02:50:32Z,World news,Former US navy secretary now Scott Morrison’s ...,"Prof Donald Winter, who advised the Australian...",A former US navy secretary who advised the Aus...
7,2021-09-16T11:32:12Z,World news,‘Stab in the back’: French fury as Australia s...,France’s foreign minister says move to buy nuc...,France has expressed fury over Australia’s sur...
8,2021-11-18T16:30:10Z,World news,‘Naughty guy’: top Chinese diplomat accuses Au...,"Exclusive: Acting ambassador to Australia, Wan...",A top Chinese diplomat has likened Australia t...
9,2021-09-20T01:11:38Z,World news,‘We felt fooled’: France still furious after A...,"‘Maybe we’re not friends,’ recalled ambassador...",French anger at the Morrison government’s deci...
10,2021-09-18T23:05:19Z,World news,Baptism of fire as Liz Truss heads to US amid ...,As France accuses the US and Australia of ‘lie...,Liz Truss is heading for a furious diplomatic ...
11,2021-10-15T01:47:07Z,World news,Nuclear agencies say it’s too early to know wh...,Rex Patrick says it’s ‘beyond comprehension’ A...,Nuclear agencies say it is too early to specul...
12,2021-10-28T12:14:32Z,World news,"Scrapping submarines deal broke trust, Macron ...",French president says Scott Morrison should pr...,The French president has told the Australian p...
13,2021-10-19T23:38:11Z,World news,IAEA chief: Aukus could set precedent for purs...,Special taskforce convened by IAEA to look int...,The head of the UN’s nuclear watchdog has said...
14,2021-11-03T06:16:49Z,World news,French ambassador says leak of Macron text ‘ne...,Jean-Pierre Thébault says Morrison government’...,The French ambassador has denounced the Austra...
15,2021-09-23T16:30:30Z,World news,Aukus: Australia sent ‘extremely satisfied’ le...,French Naval Group to invoice Australia for ab...,France has said Australian military officials ...
16,2021-09-16T02:56:11Z,World news,Aukus submarines banned from New Zealand as pa...,Experts say Aukus military deal underlines Aus...,New Zealand is not part of a new security pact...
17,2021-09-29T10:29:22Z,World news,France cool on efforts by Australia to repair ...,Élysée says future talks must have substance a...,France has said any future talks between Emman...
18,2021-09-19T17:47:54Z,World news,UK-France defence summit cancelled in Aukus row,Paris furious at scrapping of Australian subma...,A Franco-British defence ministers’ summit due...
19,2021-09-20T18:16:12Z,World news,France tries to delay EU-Australia trade deal ...,France seeks EU support to delay deal as punis...,France is seeking to enlist European Union sup...
20,2021-10-15T09:15:39Z,World news,Nuclear submarines’ uncertain delivery date me...,Vessels could be more than 50 years old by the...,Australia’s navy chief has left the door open ...
21,2021-09-16T19:48:45Z,World news,Aukus pact: UK and US battle to contain intern...,Nuclear submarine deal with Australia draws cr...,Britain and the US are battling to contain an ...
22,2021-09-16T00:17:32Z,World news,"US, UK and Australia forge military alliance t...",Aukus partnership will enable Australia to hav...,"The US, UK and Australia are setting up a tril..."
23,2021-09-22T18:56:55Z,World news,Aukus pact: France to send ambassador back to ...,US and Australia not going back on cancelled €...,France has agreed to return its ambassador to ...
24,2021-09-16T09:25:30Z,World news,China warns US-UK-Australia pact could ‘hurt t...,Aukus described as ‘exclusionary’ amid French...,"China has told the US, the UK and Australia to..."
25,2021-10-19T05:34:03Z,World news,North Korea has fired ballistic missile into s...,"Launch, possibly from a submarine, comes as US...",North Korea launched a ballistic missile – pos...
26,2021-09-20T06:35:33Z,World news,Barnaby Joyce says Australia proved its commit...,Acting prime minister says he understands Fran...,Acting prime minister Barnaby Joyce said Austr...
27,2021-09-19T05:19:51Z,World news,Australia could initially lease submarines fro...,Senior ministers confirm leasing nuclear-power...,The short-term leasing of nuclear-powered subm...
28,2021-11-03T06:17:21Z,World news,The Macron spat over Aukus submarines has taug...,The Australian PM is a relatively new player o...,As Scott Morrison flew towards Australia’s mil...
29,2021-09-18T12:14:37Z,World news,French recall of ambassadors shows extent of a...,Analysis: ties between Paris and Washington in...,The recall of the French ambassadors to Austra...
30,2021-09-18T03:15:43Z,World news,Australia ‘regrets’ France’s recall of ambassa...,Australia says it looks forward to engaging wi...,Australia has said it “notes with regret” Fran...
31,2021-11-23T01:47:04Z,World news,"As China threat rises, can Aukus alliance reco...",Questions mount about pact’s ultimate purpose ...,It was initially seen as an audacious enlistme...
32,2021-09-23T21:17:56Z,World news,Furious French defence contractor to seek comp...,Head of Naval Group attacks Australia’s ‘polit...,Australia has signed up to an empty promise by...
33,2021-09-28T14:06:47Z,World news,Greece to buy French warships in multibillion-...,Paris and Athens hail landmark accord aimed at...,Greece and France have signed a multibillion-e...
34,2021-09-16T16:09:11Z,World news,Aukus deal showing France and EU that Biden no...,Analysis: the western alliance is the main vic...,Fury in Paris at Australia’s decision to tear ...
35,2021-09-17T09:52:57Z,World news,Denmark to outlaw life sentence prisoners star...,Jails should not serve as ‘dating centres or m...,Prisoners serving life sentences in Denmark ar...
36,2021-09-19T00:28:30Z,World news,‘We thought we were mates’: French ambassador ...,Jean-Pierre Thebault was angry about Aukus as ...,The French ambassador to Australia was in a ca...
37,2021-09-17T04:51:11Z,World news,Australia dismisses China ‘outbursts’ and flag...,Australia’s defence minister says Aukus pact m...,Australia has dismissed “outbursts” from China...
38,2021-11-02T14:10:23Z,World news,French officials vent fury over Australian lea...,Confidence shattered by ‘crude’ leak of presid...,Elysée officials have expressed fury at the de...
39,2021-09-29T04:00:41Z,World news,China’s new aircraft carrier underlines need f...,Analysis: As the world’s largest navy tries to...,"In the dockyards of Shanghai, the next step in..."
40,2021-09-17T21:11:04Z,World news,France recalls ambassadors to US and Australia...,First time France has recalled a US ambassador...,France has recalled its ambassadors to the US ...
41,2021-09-18T20:19:45Z,World news,Aukus: France’s ambassador recall is ‘tip of t...,French foreign minister makes no attempt to hi...,France’s historic decision to recall its ambas...
42,2021-09-30T01:34:35Z,World news,Kim Jong-un orders hotline with the South to r...,North Korean leader said Biden offer of dialog...,Kim Jong-un has condemned a US offer of dialog...
43,2021-09-23T00:49:28Z,World news,Macron yet to take call from Australia’s Scott...,Australian PM hopes to speak with French presi...,French president Emmanuel Macron has not yet t...
44,2021-10-01T11:45:18Z,World news,Russia extends ‘foreign agents’ law to critics...,Legislation now covers citizens who study and ...,Russians who study and report on the problems ...
45,2021-09-24T14:37:38Z,World news,Johnson’s bid to mend Franco-British relations...,French president ‘awaiting PM’s proposals’ on ...,Boris Johnson has told Emmanuel Macron he want...
46,2021-09-26T01:01:11Z,World news,Kim Jong-un’s sister says North Korea open to ...,Analysts say North Korea’s apparent desire for...,The influential sister of North Korea’s leader...
47,2021-09-21T09:23:17Z,World news,Aukus: French minister bemoans lack of trust i...,Clément Beaune says Brexit fallout and secret ...,"The British-French alliance lacks trust, Franc..."
48,2021-10-02T19:00:09Z,World news,‘It will be found’: search for MH370 continues...,It is the ‘mystery that must be solved’ – seve...,Somewhere in the vast expanse of Earth’s ocean...
49,2021-11-22T00:01:10Z,World news,UK invites south-east Asian nations to G7 summ...,"The alliance between Britain, the US and Austr...",The UK has invited south-east Asian nations to...
50,2021-09-06T09:34:37Z,World news,China sends 19 aircraft into Taiwan’s air defe...,Sortie by People’s Liberation Army air force i...,China’s military sent 19 aircraft into Taiwan’...
51,2021-09-22T21:02:22Z,World news,‘Donnez-moi un break’: Johnson deepens rift wi...,UK prime minister hits out after Paris reacted...,Boris Johnson has reopened the rift with Paris...
52,2021-10-03T10:51:23Z,World news,"Draghi, Scholz or Macron? Merkel’s crown as Eu...",The three contenders to take the helm for the ...,She dominated Europe – a de facto leader in a ...
53,2021-09-24T18:00:20Z,World news,‘Treated like animals’: Julián Castro condemns...,Democrat says denying rights of Haitian people...,"Julián Castro, the former US presidential cand..."
54,2021-09-13T17:10:45Z,World news,"Why takeovers, rather than arms, may be the ta...","In the second in our Britain For Sale series, ...",Defence industry bosses have missed out on a y...
55,2021-09-24T10:00:15Z,World news,Biden to rally regional support for China cont...,"Biden will meet leaders of Australia, India an...",Joe Biden will host the first in-person summit...
56,2021-09-17T05:21:15Z,World news,Friday briefing: Aukus pact backlash grows,Concerns the alliance could lead to the UK bei...,Morning everyone. I’m Martin Farrer and these ...
57,2021-10-20T05:30:00Z,World news,Wednesday briefing: Time for plan B to stop Co...,NHS in danger of ‘stumbling into crisis’ as wi...,"Hello, Warren Murray helping you start Wednesd..."
58,2021-09-21T22:29:41Z,World news,UN: Joe Biden and Boris Johnson meet at White ...,,

What are the strategies to remove irrelevant articles? 

**Task**: Remove irrelevant articles before next step.

In [11]:
# for example:
df = df[df['Title'].str.lower().str.contains('submarine')]
df

,Date,Section,Title,Subtitle,Body
0,2021-10-31T19:27:45Z,World news,Macron accuses Australian PM of lying over sub...,French president criticises Scott Morrison and...,Emmanuel Macron has accused the Australian pri...
1,2021-10-07T16:39:54Z,World news,Aukus: French contractor ‘astonished’ at cance...,Head of Naval Group reiterates company’s ‘stup...,The head of the French defence contractor Nava...
2,2021-11-08T16:30:35Z,World news,Australia promises jobs to workers stranded by...,Defence industry minister Melissa Price tells ...,“Each and every” skilled shipbuilding worker a...
3,2021-10-29T17:06:48Z,World news,Biden admits to Macron the US was ‘clumsy’ in ...,American president moves to repair relationshi...,Joe Biden has moved to repair his damaged pers...
4,2021-10-01T09:00:58Z,World news,Fears Australia’s France submarine snub could ...,Opposition accuses Scott Morrison of failing ‘...,The postponement of trade talks between the Eu...
5,2021-10-28T04:39:00Z,World news,Australia’s foreign minister to meet French am...,Marise Payne says she regrets France’s ‘deep d...,Australia’s foreign minister will meet with th...
6,2021-09-29T02:50:32Z,World news,Former US navy secretary now Scott Morrison’s ...,"Prof Donald Winter, who advised the Australian...",A former US navy secretary who advised the Aus...
7,2021-09-16T11:32:12Z,World news,‘Stab in the back’: French fury as Australia s...,France’s foreign minister says move to buy nuc...,France has expressed fury over Australia’s sur...
8,2021-11-18T16:30:10Z,World news,‘Naughty guy’: top Chinese diplomat accuses Au...,"Exclusive: Acting ambassador to Australia, Wan...",A top Chinese diplomat has likened Australia t...
9,2021-09-20T01:11:38Z,World news,‘We felt fooled’: France still furious after A...,"‘Maybe we’re not friends,’ recalled ambassador...",French anger at the Morrison government’s deci...
10,2021-09-18T23:05:19Z,World news,Baptism of fire as Liz Truss heads to US amid ...,As France accuses the US and Australia of ‘lie...,Liz Truss is heading for a furious diplomatic ...
11,2021-10-15T01:47:07Z,World news,Nuclear agencies say it’s too early to know wh...,Rex Patrick says it’s ‘beyond comprehension’ A...,Nuclear agencies say it is too early to specul...
12,2021-10-28T12:14:32Z,World news,"Scrapping submarines deal broke trust, Macron ...",French president says Scott Morrison should pr...,The French president has told the Australian p...
13,2021-10-19T23:38:11Z,World news,IAEA chief: Aukus could set precedent for purs...,Special taskforce convened by IAEA to look int...,The head of the UN’s nuclear watchdog has said...
14,2021-11-03T06:16:49Z,World news,French ambassador says leak of Macron text ‘ne...,Jean-Pierre Thébault says Morrison government’...,The French ambassador has denounced the Austra...
16,2021-09-16T02:56:11Z,World news,Aukus submarines banned from New Zealand as pa...,Experts say Aukus military deal underlines Aus...,New Zealand is not part of a new security pact...
20,2021-10-15T09:15:39Z,World news,Nuclear submarines’ uncertain delivery date me...,Vessels could be more than 50 years old by the...,Australia’s navy chief has left the door open ...
27,2021-09-19T05:19:51Z,World news,Australia could initially lease submarines fro...,Senior ministers confirm leasing nuclear-power...,The short-term leasing of nuclear-powered subm...
28,2021-11-03T06:17:21Z,World news,The Macron spat over Aukus submarines has taug...,The Australian PM is a relatively new player o...,As Scott Morrison flew towards Australia’s mil...

### 3. Analysis

Information extraction?

#### Inspect the data

Read a few articles at random to get a feel for what is important to analyse.

#### One approach - a basic sentiment analysis that looks for positive and negative words in the text

In [12]:
# Define lists of positive and negative words
positive_words = ["good", "positive", "excellent", "success"] # add words you think are good indicators
negative_words = ["bad", "poor", "negative", "disappointing", "angry"]


# Function to calculate a basic sentiment score
def analyze_sentiment(article):
    positive_count = 0
    negative_count = 0
    
    # Convert article to lowercase and split into words
    words = article.lower().split()
    
    # Count occurrences of positive and negative words
    for word in words:
        if word in positive_words:
            positive_count += 1
        if word in negative_words:
            negative_count += 1
            
    # Compute sentiment score
    sentiment_score = positive_count - negative_count
    return sentiment_score

In [13]:
# Analyze the articles

# Create a list of article bodies from the df column
article_body_texts = df["Body"].tolist()

# Loop through and run the analyze_sentiment function on each
for article_text in article_body_texts:
    
    score = analyze_sentiment(article_text)

    # Print sentiment score
    print(f"Sentiment Score: {score}")

Sentiment Score: 0
Sentiment Score: 0
Sentiment Score: 0
Sentiment Score: 1
Sentiment Score: 0
Sentiment Score: 0
Sentiment Score: 0
Sentiment Score: -3
Sentiment Score: -1
Sentiment Score: 0
Sentiment Score: 0
Sentiment Score: 0
Sentiment Score: 0
Sentiment Score: 0
Sentiment Score: 0
Sentiment Score: 0
Sentiment Score: 1
Sentiment Score: 0
Sentiment Score: -1

#### Combine the scores and do some analysis

##### Tip: You could add them as a new column of your existing df

In [14]:
???

Object `?` not found.

### 4. Visualisation

In [15]:
???

Object `?` not found.

### 5. Insights

What might be some limitations of how you analysed the data?

#

# Scrape some data from the web to include as background in your final report

Use code similar to that in this week's lecture session to scrape some data from the web relevant to the submarine issue.

Suggestion: A list of current Australian submarines with their names and launch dates scraped from the web like the one at https://en.wikipedia.org/wiki/Collins-class_submarine#Submarines_in_class)